name: pkgcheck
description: Run pkgcheck over an ebuild repository
inputs:
  args:
    description: Arguments to pass to pkgcheck
    required: false
    default: ''
  pkgs:
    description: Target packages to install via pip
    required: false
    default: pkgcore>=0.11.8 pkgcheck>=0.9.6
runs:
  using: node12
  main: dist/index.js
